export const produtosReais = [
  "Níquel  Placas",
  "Níquel Catodos",
  "Níquel Full Plate Plating",
  "Coque Metalúrgico Leve",
  "Grafite",
  "Carbeto de Silício",
  "Silício Metálico (SiMe), Rebarba, 10-60mm",
  "Cálcio Silício (CaSi)",
  "Zinco",
  "Tungstênio Metálico",
  "Ferro Molibidênio 0,55 <325 Mesh",
  "Sucata de Alumínio",
  "Silício Metálico (SiMe)",
  "Silício Metálico Contaminado",
  "Resíduo Amido",
  "Pentóxido de Vanádio",
  "Níquel Rounds",
  "Níquel",
  "Níquel Full Plate",
  "Nucleante  2-10mm",
  "Nucleante  0,5-3,36mm",
  "Molibdenita",
  "Mn Eletrolítico Nitrogenado",
  "Magnésio Metálico",
  "Manganês (Mn)",
  "Inoculante CZ",
  "Inoculante C1BB",
  "Inoculante C1",
  "Grafite  Granulado",
  "Ferro Vanadio",
  "Ferro Vanádio",
  "Ferro Tungstênio",
  "Ferro Titânio",
  "Ferro Silício Zircônio",
  "Ferro Silício Cálcio Alumínio Manganês",
  "Ferro Silício Cálcio Alumínio Estrôncio",
  "Ferro Silício Cálcio Alumínio Bearing",
  "Ferro Silício Cálcio Alumínio Bário",
  "Ferro Silício (FeSi)",
  "Ferro Silico Manganês (FeSiMn)",
  "Ferro Molibdênio",
  "Ferro Manganês (FeMn) M/C",
  "Ferro Manganês (FeMn) B/C",
  "Ferro Manganês (FeMn) A/C",
  "Ferro Fósforo (FeP)",
  "Ferro Cromo (FeCr) B/C Inox",
  "Ferro Cromo (FeCr) B/C",
  "Ferro Cromo (FeCr) A/C",
  "Ferro Boro",
  "FeSiMg CW 13",
  "FeSiMg - Liga 4",
  "FeSiMg - Liga 1",
  "FeSiCaAlBaMn",
  "Escória FeSi",
  "Escória de Ferro",
  "Escória de Silício",
  "Enxofre",
  "Enxofre Seco",
  "Cálcio Silício Manganês",
  "Cálcio Silício (CaSi)  10-60 mm",
  "Cromo Metálico",
  "Cobre Vergalhao Picotado",
  "Concentrado de Cerium",
  "Cobre Vergalhão",
  "Cobalto",
  "Briquete de Lama",
  "Chapelim",
];